
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMINISTRADOR1
 */
public class Principal extends javax.swing.JFrame {
static Random r = new Random();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
          Object[][] matriz = new Object[13][33];
        matriz = Lectura();
        Imprimir(matriz);
        
        
        jugador();
        listaBa.add(new Bana ("@"));
        listasub.add(new SubBana("X"));
        
        try {
            admB.cargarArchivo();
            
            for (Bana t : admB.getListaBana()) {
                listaBa.add(t);
            }

        } catch (Exception e) {
        }
        try {
            admSub.cargarArchivo();
            
            for (SubBana t : admSub.getListasub()) {
                listasub.add(t);
            }

        } catch (Exception e) {
        }
        try {
            admJug.cargarArchivo();
            
            for ( Jugadores t : admJug.getListaJ()) {
                listaj.add(t);
            }

        } catch (Exception e) {
        }
        for (int i = 0; i < listaj.size(); i++) {
            System.out.println(listaj.get(i));
        }
         String modelo_combo = Tablero.getText();
        for (int i = 0; i < listaj.size(); i++) {
            modelo_combo = (listaj.get(i).getJ());
        }
        Tablero.setText(modelo_combo);
        
        for (int i = 0; i < listaBa.size(); i++) {
            System.out.println(listaBa.get(i));
        }
         String modelo_c = Tablero.getText();
        for (int i = 0; i < listaBa.size(); i++) {
            modelo_c = (listaBa.get(i).getB());
        }
        Tablero.setText(modelo_c);
        
        for (int i = 0; i < listasub.size(); i++) {
            System.out.println(listasub.get(i));
        }
         String modelo = Tablero.getText();
        for (int i = 0; i < listasub.size(); i++) {
            modelo= (listasub.get(i).getSb());
        }
        Tablero.setText(modelo_c);
    }
    public void Imprimir(Object[][] matriz) {
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[i].length; j++) {
                System.out.print("[" + matriz[i][j] + "]" + " ");
            }
            System.out.println();
        }
    }
      public static Object[][] Lectura() {
        Object[][] llena = new Object[10][10];

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                llena[i][j] = "  ";
            }
        }
  
        return llena;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablero = new javax.swing.JTextArea();
        Comando = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Cargar = new javax.swing.JButton();
        Comenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Banana Eats");

        Tablero.setColumns(20);
        Tablero.setRows(5);
        Tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablero);

        Guardar.setText("Guardar");

        Cargar.setText("Cargar");

        Comenzar.setText("Comenzar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(Cargar)
                                .addGap(68, 68, 68)
                                .addComponent(Comenzar))
                            .addComponent(jScrollPane1)
                            .addComponent(Comando))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cargar)
                    .addComponent(Comenzar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableroMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TableroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public void jugador(){
        listaj.add(new Jugadores ("O"));
        listaj.add(new Jugadores ("O"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    private javax.swing.JTextField Comando;
    private javax.swing.JButton Comenzar;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextArea Tablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
 ArrayList<Bana> listaBa = new ArrayList();
    ArrayList<SubBana> listasub = new ArrayList();
    ArrayList<Jugadores> listaj = new ArrayList();
    
    
    AdminB admB = new AdminB("./BANANA.txt");
    AdminSB admSub = new AdminSB("./SUBBANANA.txt");
    AdminJug admJug = new AdminJug("./Jugadores.txt");
    

}
